#!/usr/bin/env python3
"""Audit every candidate EvoGym task against every fixed morphology."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import platform
from time import perf_counter
import numpy as np

from thesis_testing.evogym_contract import inspect_env, make_env
from thesis_testing.morphology import MorphologySpec, get_reference_morphology
from thesis_testing.protocol import ScientificCondition, load_scientific_protocol
from thesis_testing.reproducibility import collect_runtime_manifest
from thesis_testing.smoke_rollout import build_smoke_policy, run_rollout
from thesis_testing.task_catalog import TaskSpec, get_task_spec


@dataclass(frozen=True)
class AuditRow:
    env_id: str
    difficulty: str
    morphology: str
    compatible: bool
    horizon: int | None = None
    observation_dim: int | None = None
    action_dim: int | None = None
    actuator_indices: tuple[int, ...] = ()
    action_bounds: str = "-"
    reset_shape: tuple[int, ...] = ()
    termination_step: int | None = None
    termination_kind: str = "-"
    total_reward: float | None = None
    simulation_instability: bool | None = None
    error: str | None = None


def audit_one(task: TaskSpec, morphology: MorphologySpec, seed: int) -> AuditRow:
    env = None
    try:
        construction_start = perf_counter()
        env = make_env(task.env_id, morphology)
        _ = perf_counter() - construction_start
        contract = inspect_env(env)
        if contract.max_episode_steps != task.expected_horizon:
            raise ValueError(
                f"registered horizon {contract.max_episode_steps} != catalog "
                f"{task.expected_horizon}"
            )
        if not np.array_equal(contract.action_low, np.full(contract.action_dim, 0.6)):
            raise ValueError("action lower bounds differ from pinned EvoGym source")
        if not np.array_equal(contract.action_high, np.full(contract.action_dim, 1.6)):
            raise ValueError("action upper bounds differ from pinned EvoGym source")

        policy = build_smoke_policy(contract.observation_dim, contract.action_dim, seed)
        result = run_rollout(env, policy, seed, record_trace=False)
        env = None  # run_rollout closes it
        if result.terminated and result.truncated:
            termination_kind = "terminated+truncated"
        elif result.terminated:
            termination_kind = "terminated"
        elif result.truncated:
            termination_kind = "truncated"
        else:
            termination_kind = "none"
        return AuditRow(
            env_id=task.env_id,
            difficulty=task.difficulty,
            morphology=morphology.name,
            compatible=True,
            horizon=contract.max_episode_steps,
            observation_dim=contract.observation_dim,
            action_dim=contract.action_dim,
            actuator_indices=tuple(int(value) for value in contract.actuator_indices),
            action_bounds="[0.6, 1.6]",
            reset_shape=result.initial_observation.shape,
            termination_step=result.episode_length,
            termination_kind=termination_kind,
            total_reward=result.total_reward,
            simulation_instability=result.simulation_instability,
        )
    except Exception as error:  # audit output must preserve incompatibilities
        return AuditRow(
            env_id=task.env_id,
            difficulty=task.difficulty,
            morphology=morphology.name,
            compatible=False,
            error=f"{type(error).__name__}: {error}",
        )
    finally:
        if env is not None:
            env.close()


def select_conditions(
    rows: list[AuditRow], conditions: tuple[ScientificCondition, ...]
) -> tuple[ScientificCondition, ...]:
    for condition in conditions:
        if not any(
            row.env_id == condition.task
            and row.morphology == condition.morphology
            and row.compatible
            for row in rows
        ):
            raise RuntimeError(f"official condition is incompatible: {condition.label}")
    return conditions


def render_markdown(
    rows: list[AuditRow], selected: tuple[ScientificCondition, ...], seed: int
) -> str:
    manifest = collect_runtime_manifest(seed)
    lines = [
        "# EvoGym Task Audit",
        "",
        "> Generated by `scripts/audit_tasks.py`; do not edit result rows manually.",
        "",
        "## Audit runtime",
        "",
        f"- Python: `{manifest['python_version']}`",
        f"- Platform: `{platform.platform()}`",
        f"- NumPy: `{manifest['numpy_version']}`",
        f"- PyTorch: `{manifest['torch_version']}`",
        f"- Gymnasium: `{manifest['gymnasium_version']}`",
        f"- EvoGym: `{manifest['evogym_version']}`",
        f"- EvoGym compiled-simulator diagnostic: `{manifest['evogym_simulator_diagnostic_version']}`",
        f"- EvoGym inspected SHA: `{manifest['evogym_upstream_sha']}`",
        f"- Seed: `{seed}`",
        "",
        "## Results",
        "",
        "A successful row means construction, Gymnasium reset, contract validation, and a complete headless smoke rollout all succeeded. `truncated` indicates the registered `TimeLimit`; `terminated` is an environment termination. EvoGym 2.0.0 leaves `info` empty, so simulation instability is detected from its explicit instability diagnostic.",
        "",
        "| Task | Difficulty | Morphology | Compatible | Horizon | O | A | Actuator indices | Bounds | Reset shape | Stop step | Stop kind | Smoke reward | Unstable | Error |",
        "|---|---:|---|---:|---:|---:|---:|---|---|---|---:|---|---:|---:|---|",
    ]
    for row in rows:
        reward = "-" if row.total_reward is None else f"{row.total_reward:.9f}"
        unstable = "-" if row.simulation_instability is None else str(row.simulation_instability)
        lines.append(
            "| "
            + " | ".join(
                (
                    row.env_id,
                    row.difficulty,
                    row.morphology,
                    str(row.compatible),
                    str(row.horizon or "-"),
                    str(row.observation_dim or "-"),
                    str(row.action_dim or "-"),
                    str(list(row.actuator_indices)) if row.actuator_indices else "-",
                    row.action_bounds,
                    str(row.reset_shape) if row.reset_shape else "-",
                    str(row.termination_step or "-"),
                    row.termination_kind,
                    reward,
                    unstable,
                    (row.error or "-").replace("|", "\\|"),
                )
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Selected task set",
            "",
            "Every official task/morphology condition constructs and completes a smoke rollout:",
            "",
        ]
    )
    lines.extend(
        f"- `{condition.task}` with `{condition.morphology}` "
        f"({get_task_spec(condition.task).difficulty})"
        for condition in selected
    )
    lines.extend(
        [
            "",
            "`Carrier-v0` is registered and supported but Gymnasium warns that version `v0` is deprecated. Dimensions are intentionally reported per instantiated task and morphology rather than inferred from formulas.",
            "",
            "## Pinned-source validations",
            "",
            "- Registered horizons equal 500 for Walker/Carrier/Jumper and 300 for Thrower.",
            "- Every action dimension equals the instantiated robot actuator count.",
            "- Every action bound is finite and equals `[0.6, 1.6]`.",
            "- Reset observations and every step observation match `observation_space.shape`.",
            "- Every step used the Gymnasium five-value API and stopped on `terminated or truncated`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    output = Path("artifacts/task_audit.md")
    seed = 17
    conditions = load_scientific_protocol().conditions
    rows = [
        audit_one(get_task_spec(condition.task), get_reference_morphology(condition.morphology), seed)
        for condition in conditions
    ]
    selected = select_conditions(rows, conditions)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_markdown(rows, selected, seed))
    print(f"wrote {output} with {len(rows)} task/morphology rows")


if __name__ == "__main__":
    main()
